feat: Added doctrine/dbal v4.0.
php-casbin/dbal-adapter pull request #7
Opened 2024-04-11 08:24 UTC by tasselchof

fix: #6

2024-04-12 16:54 UTC, leeqvip commented
@tasselchof  Please make it compatible with PHP7.1, it's not very complicated.

2024-04-12 17:35 UTC, tasselchof commented
> @tasselchof Please make it compatible with PHP7.1, it's not very complicated.

Except doctrine/dbal:^3.8 requires at least PHP 7.4, so it is impossible to do this. I think PHP 7 should be dropped from supported versions.

2024-04-14 04:50 UTC, leeqvip requested changes

2024-04-14 04:50 UTC, leeqvip commented on src/Adapter.php
> +        $sm = $this->connection->createSchemaManager();
You can make some assertions here to ensure compatibility with lower versions.

2024-04-14 04:50 UTC, leeqvip commented on src/Adapter.php
> +        $stmt = $queryBuilder->select('p_type', 'v0', 'v1', 'v2', 'v3', 'v4', 'v5')->from($this->policyTableName)->executeQuery();
And here

2024-05-29 03:02 UTC, hsluoyz commented
Fix: https://github.com/php-casbin/dbal-adapter/issues/6

2024-06-10 15:21 UTC, merged

2024-06-10 15:22 UTC, leeqvip commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/dbal-adapter/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: